- name: Install Elastic Security integration templates
  uri:
    url: "http://localhost:{{ elasticsearch_port }}/_index_template/security-events"
    method: PUT
    user: "elastic"
    password: "{{ elastic_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      index_patterns: ["logs-endpoint.events.*", "logs-windows.*", "logs-system.*"]
      priority: 200
      template:
        settings:
          number_of_shards: 1
          number_of_replicas: 0
          refresh_interval: "5s"
          index:
            max_result_window: 100000
        mappings:
          properties:
            "@timestamp":
              type: date
            event:
              properties:
                action:
                  type: keyword
                category:
                  type: keyword
                code:
                  type: keyword
                dataset:
                  type: keyword
                kind:
                  type: keyword
                module:
                  type: keyword
                outcome:
                  type: keyword
                provider:
                  type: keyword
                severity:
                  type: long
                type:
                  type: keyword
            host:
              properties:
                hostname:
                  type: keyword
                  fields:
                    text:
                      type: text
                name:
                  type: keyword
                os:
                  properties:
                    family:
                      type: keyword
                    name:
                      type: keyword
                    version:
                      type: keyword
            process:
              properties:
                name:
                  type: keyword
                pid:
                  type: long
                ppid:
                  type: long
                executable:
                  type: keyword
                command_line:
                  type: text
                  fields:
                    keyword:
                      type: keyword
                hash:
                  properties:
                    md5:
                      type: keyword
                    sha256:
                      type: keyword
            user:
              properties:
                name:
                  type: keyword
                domain:
                  type: keyword
                id:
                  type: keyword
            winlog:
              properties:
                api:
                  type: keyword
                channel:
                  type: keyword
                computer_name:
                  type: keyword
                event_id:
                  type: keyword
                provider_name:
                  type: keyword
                record_id:
                  type: keyword
                task:
                  type: keyword
                event_data:
                  type: object
                  enabled: true
  register: security_template_result
  until: security_template_result.status == 200
  retries: 5
  delay: 10

- name: Configure Windows Event Log retention policy
  uri:
    url: "http://localhost:{{ elasticsearch_port }}/_ilm/policy/windows-logs-policy"
    method: PUT
    user: "elastic"
    password: "{{ elastic_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      policy:
        phases:
          hot:
            actions:
              rollover:
                max_size: "10gb"
                max_age: "7d"
          warm:
            min_age: "7d"
            actions:
              allocate:
                number_of_replicas: 0
          cold:
            min_age: "30d"
            actions:
              allocate:
                number_of_replicas: 0
          delete:
            min_age: "90d"
            actions:
              delete: {}
  register: ilm_policy_result
  until: ilm_policy_result.status == 200
  retries: 5
  delay: 10