- name: Install and configure Elastic Stack
  hosts: elastic_server
  become: yes
  roles:
    - { role: 'elasticsearch', tags: 'elasticsearch' }
    - { role: 'kibana', tags: 'kibana' }
    - { role: 'logstash', tags: 'logstash' }

- name: Install Elastic Agent on Windows Domain Machines
  hosts: elastic_agents
  roles:
    - { role: 'elastic_agent_windows', tags: 'elastic_agent_windows' }
  vars:
    elastic_server_host: "{{ hostvars['elastic']['ansible_host'] }}"