boxes.append(
    { :name => "ELK-EDR",
      :ip => "{{ip_range}}.50",
      :box => "bento/ubuntu-22.04",
      :os => "linux",
      :cpus => 4,                    # Increased for Elastic Stack + Fleet
      :mem => 8192,                  # 8GB RAM for Elastic Stack + Fleet Server
      :forwarded_port => [ 
        {:guest => 22, :host => 2210, :id => "ssh"},
        {:guest => 5601, :host => 5601, :id => "kibana"},      # Kibana Web UI
        {:guest => 9200, :host => 9200, :id => "elasticsearch"}, # Elasticsearch API
        {:guest => 8220, :host => 8220, :id => "fleet"}         # Fleet Server
      ]
    }
)
